name: assignment
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.3
  page_view_dot_indicator: ^2.3.0
  badges: ^3.1.2
  google_fonts: ^6.2.1
  awesome_bottom_bar: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

